### ISSUE TITLE
Test completes without launching the app in android 11

### ISSUE THREAD

**Issue by nbdsunny** [leancodepl/patrol#1575]
### Steps to reproduce

1. Clone https://github.com/nbdsunny/integration_test_example.git
2. Attach android 11 device (Samsung A50 in my case).
3. Run the test using the command: patrol test --target integration_test/example_test.dart --verbose

### Actual results

Based on the logs, the test is completed. But the app does not launch in the android 11 device during the test. I can see a notification of `AndroidX Test Services` for some moment. This problem doesn't occur on an android 10 device. The app launches during the test on that device.

### Logs

<details>
<summary>Logs</summary>

```
You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

Verbose mode enabled. More logs will be printed.
Received 1 test target(s)
Received test target: /home/nabid_admin/Projects/Flutter/integration_test_example/integration_test/example_test.dart
Generated entrypoint /home/nabid_admin/Projects/Flutter/integration_test_example/integration_test/test_bundle.dart with 1 bundled test(s)
$ flutter --no-version-check devices --machine
No device specified, using the first one (R28M30RPKNB)
Received 1 device(s) to run on
Received device: R28M30RPKNB
Received 7 --dart-define(s) (0 custom, 7 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_PACKAGE_NAME=com.example.integration_test_example
Received internal --dart-define: PATROL_APP_BUNDLE_ID=com.example.integration_test_example
Received internal --dart-define: PATROL_ANDROID_APP_NAME=integration_test_example
Received internal --dart-define: PATROL_IOS_APP_NAME=integration_test_example
Received internal --dart-define: INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE=false
Received internal --dart-define: PATROL_TEST_LABEL_ENABLED=true
• Building apk with entrypoint test_bundle.dart...
$ ./gradlew :app:assembleDebug -Ptarget=/home/nabid_admin/Projects/Flutter/integration_test_example/integration_test/test_bundle.dart -Pdart-defines=UEFUUk9MX1dBSVQ9MA==,UEFUUk9MX0FQUF9QQUNLQUdFX05BTUU9Y29tLmV4YW1wbGUuaW50ZWdyYXRpb25fdGVzdF9leGFtcGxl,UEFUUk9MX0FQUF9CVU5ETEVfSUQ9Y29tLmV4YW1wbGUuaW50ZWdyYXRpb25fdGVzdF9leGFtcGxl,UEFUUk9MX0FORFJPSURfQVBQX05BTUU9aW50ZWdyYXRpb25fdGVzdF9leGFtcGxl,UEFUUk9MX0lPU19BUFBfTkFNRT1pbnRlZ3JhdGlvbl90ZXN0X2V4YW1wbGU=,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl,UEFUUk9MX1RFU1RfTEFCRUxfRU5BQkxFRD10cnVl
        : WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 34
        : 
        : This Android Gradle plugin (7.1.2) was tested up to compileSdk = 32
        : 
        : This warning can be suppressed by adding
        :     android.suppressUnsupportedCompileSdk=34
        : to this project's gradle.properties
        : 
        : The build will continue, but you are strongly encouraged to update your project to
        : use a newer Android Gradle Plugin that has been tested with compileSdk = 34
        : WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 33
        : 
        : This Android Gradle plugin (7.1.2) was tested up to compileSdk = 32
        : 
        : This warning can be suppressed by adding
        :     android.suppressUnsupportedCompileSdk=33
        : to this project's gradle.properties
        : 
        : The build will continue, but you are strongly encouraged to update your project to
        : use a newer Android Gradle Plugin that has been tested with compileSdk = 33
        : > Task :app:preBuild UP-TO-DATE
        : > Task :app:preDebugBuild UP-TO-DATE
        : > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
        : > Task :app:compileFlutterBuildDebug UP-TO-DATE
        : > Task :app:packLibsflutterBuildDebug UP-TO-DATE
        : > Task :integration_test:preBuild UP-TO-DATE
        : > Task :integration_test:preDebugBuild UP-TO-DATE
        : > Task :integration_test:compileDebugAidl NO-SOURCE
        : > Task :patrol:preBuild UP-TO-DATE
        : > Task :patrol:preDebugBuild UP-TO-DATE
        : > Task :patrol:compileDebugAidl NO-SOURCE
        : > Task :app:compileDebugAidl NO-SOURCE
        : > Task :integration_test:packageDebugRenderscript NO-SOURCE
        : > Task :patrol:packageDebugRenderscript NO-SOURCE
        : > Task :app:compileDebugRenderscript NO-SOURCE
        : > Task :app:generateDebugBuildConfig UP-TO-DATE
        : > Task :integration_test:writeDebugAarMetadata UP-TO-DATE
        : > Task :patrol:writeDebugAarMetadata UP-TO-DATE
        : > Task :app:checkDebugAarMetadata UP-TO-DATE
        : > Task :app:cleanMergeDebugAssets
        : > Task :app:mergeDebugShaders UP-TO-DATE
        : > Task :app:compileDebugShaders NO-SOURCE
        : > Task :app:generateDebugAssets UP-TO-DATE
        : > Task :integration_test:mergeDebugShaders UP-TO-DATE
        : > Task :integration_test:compileDebugShaders NO-SOURCE
        : > Task :integration_test:generateDebugAssets UP-TO-DATE
        : > Task :integration_test:packageDebugAssets UP-TO-DATE
        : > Task :patrol:mergeDebugShaders UP-TO-DATE
        : > Task :patrol:compileDebugShaders NO-SOURCE
        : > Task :patrol:generateDebugAssets UP-TO-DATE
        : > Task :patrol:packageDebugAssets UP-TO-DATE
        : > Task :app:mergeDebugAssets
        : > Task :app:copyFlutterAssetsDebug
        : > Task :app:generateDebugResValues UP-TO-DATE
        : > Task :app:generateDebugResources UP-TO-DATE
        : > Task :integration_test:compileDebugRenderscript NO-SOURCE
        : > Task :integration_test:generateDebugResValues UP-TO-DATE
        : > Task :integration_test:generateDebugResources UP-TO-DATE
        : > Task :integration_test:packageDebugResources UP-TO-DATE
        : > Task :patrol:compileDebugRenderscript NO-SOURCE
        : > Task :patrol:generateDebugResValues UP-TO-DATE
        : > Task :patrol:generateDebugResources UP-TO-DATE
        : > Task :patrol:packageDebugResources UP-TO-DATE
        : > Task :app:mergeDebugResources UP-TO-DATE
        : > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
        : > Task :app:extractDeepLinksDebug UP-TO-DATE
        : > Task :integration_test:extractDeepLinksDebug UP-TO-DATE
        : > Task :integration_test:processDebugManifest UP-TO-DATE
        : > Task :patrol:extractDeepLinksDebug UP-TO-DATE
        : > Task :patrol:processDebugManifest UP-TO-DATE
        : > Task :app:processDebugMainManifest UP-TO-DATE
        : > Task :app:processDebugManifest UP-TO-DATE
        : > Task :app:processDebugManifestForPackage UP-TO-DATE
        : > Task :integration_test:compileDebugLibraryResources UP-TO-DATE
        : > Task :integration_test:parseDebugLocalResources UP-TO-DATE
        : > Task :integration_test:generateDebugRFile UP-TO-DATE
        : > Task :patrol:compileDebugLibraryResources UP-TO-DATE
        : > Task :patrol:parseDebugLocalResources UP-TO-DATE
        : > Task :patrol:generateDebugRFile UP-TO-DATE
        : > Task :app:processDebugResources UP-TO-DATE
        : > Task :integration_test:generateDebugBuildConfig UP-TO-DATE
        : > Task :integration_test:javaPreCompileDebug UP-TO-DATE
        : > Task :integration_test:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :integration_test:bundleLibCompileToJarDebug UP-TO-DATE
        : > Task :patrol:generateDebugBuildConfig UP-TO-DATE
        : > Task :patrol:compileDebugKotlin UP-TO-DATE
        : > Task :patrol:javaPreCompileDebug UP-TO-DATE
        : > Task :patrol:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :patrol:bundleLibCompileToJarDebug UP-TO-DATE
        : > Task :app:compileDebugKotlin UP-TO-DATE
        : > Task :app:javaPreCompileDebug UP-TO-DATE
        : > Task :app:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :app:compressDebugAssets UP-TO-DATE
        : > Task :app:processDebugJavaRes NO-SOURCE
        : > Task :integration_test:processDebugJavaRes NO-SOURCE
        : > Task :integration_test:bundleLibResDebug NO-SOURCE
        : > Task :patrol:processDebugJavaRes NO-SOURCE
        : > Task :patrol:bundleLibResDebug UP-TO-DATE
        : > Task :app:mergeDebugJavaResource UP-TO-DATE
        : > Task :app:checkDebugDuplicateClasses UP-TO-DATE
        : > Task :app:desugarDebugFileDependencies UP-TO-DATE
        : > Task :app:mergeExtDexDebug UP-TO-DATE
        : > Task :integration_test:bundleLibRuntimeToJarDebug UP-TO-DATE
        : > Task :patrol:bundleLibRuntimeToJarDebug UP-TO-DATE
        : > Task :app:dexBuilderDebug UP-TO-DATE
        : > Task :app:mergeLibDexDebug UP-TO-DATE
        : > Task :app:mergeProjectDexDebug UP-TO-DATE
        : > Task :app:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :integration_test:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :integration_test:mergeDebugNativeLibs NO-SOURCE
        : > Task :integration_test:copyDebugJniLibsProjectOnly UP-TO-DATE
        : > Task :patrol:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :patrol:mergeDebugNativeLibs NO-SOURCE
        : > Task :patrol:copyDebugJniLibsProjectOnly UP-TO-DATE
        : > Task :app:mergeDebugNativeLibs UP-TO-DATE
        : > Task :app:stripDebugDebugSymbols UP-TO-DATE
        : > Task :app:validateSigningDebug UP-TO-DATE
        : > Task :app:writeDebugAppMetadata UP-TO-DATE
        : > Task :app:writeDebugSigningConfigVersions UP-TO-DATE
        : > Task :app:packageDebug UP-TO-DATE
        : > Task :app:createDebugApkListingFileRedirect UP-TO-DATE
        : > Task :app:assembleDebug
        : 
        : BUILD SUCCESSFUL in 8s
        : 72 actionable tasks: 4 executed, 68 up-to-date
$ ./gradlew :app:assembleDebugAndroidTest -Ptarget=/home/nabid_admin/Projects/Flutter/integration_test_example/integration_test/test_bundle.dart -Pdart-defines=UEFUUk9MX1dBSVQ9MA==,UEFUUk9MX0FQUF9QQUNLQUdFX05BTUU9Y29tLmV4YW1wbGUuaW50ZWdyYXRpb25fdGVzdF9leGFtcGxl,UEFUUk9MX0FQUF9CVU5ETEVfSUQ9Y29tLmV4YW1wbGUuaW50ZWdyYXRpb25fdGVzdF9leGFtcGxl,UEFUUk9MX0FORFJPSURfQVBQX05BTUU9aW50ZWdyYXRpb25fdGVzdF9leGFtcGxl,UEFUUk9MX0lPU19BUFBfTkFNRT1pbnRlZ3JhdGlvbl90ZXN0X2V4YW1wbGU=,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl,UEFUUk9MX1RFU1RfTEFCRUxfRU5BQkxFRD10cnVl
        : WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 34
        : 
        : This Android Gradle plugin (7.1.2) was tested up to compileSdk = 32
        : 
        : This warning can be suppressed by adding
        :     android.suppressUnsupportedCompileSdk=34
        : to this project's gradle.properties
        : 
        : The build will continue, but you are strongly encouraged to update your project to
        : use a newer Android Gradle Plugin that has been tested with compileSdk = 34
        : WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 33
        : 
        : This Android Gradle plugin (7.1.2) was tested up to compileSdk = 32
        : 
        : This warning can be suppressed by adding
        :     android.suppressUnsupportedCompileSdk=33
        : to this project's gradle.properties
        : 
        : The build will continue, but you are strongly encouraged to update your project to
        : use a newer Android Gradle Plugin that has been tested with compileSdk = 33
        : > Task :app:preBuild UP-TO-DATE
        : > Task :app:preDebugBuild UP-TO-DATE
        : > Task :integration_test:preBuild UP-TO-DATE
        : > Task :integration_test:preDebugBuild UP-TO-DATE
        : > Task :integration_test:compileDebugAidl NO-SOURCE
        : > Task :patrol:preBuild UP-TO-DATE
        : > Task :patrol:preDebugBuild UP-TO-DATE
        : > Task :patrol:compileDebugAidl NO-SOURCE
        : > Task :app:compileDebugAidl NO-SOURCE
        : > Task :integration_test:packageDebugRenderscript NO-SOURCE
        : > Task :patrol:packageDebugRenderscript NO-SOURCE
        : > Task :app:compileDebugRenderscript NO-SOURCE
        : > Task :app:generateDebugBuildConfig UP-TO-DATE
        : > Task :integration_test:writeDebugAarMetadata UP-TO-DATE
        : > Task :patrol:writeDebugAarMetadata UP-TO-DATE
        : > Task :app:checkDebugAarMetadata UP-TO-DATE
        : > Task :app:generateDebugResValues UP-TO-DATE
        : > Task :app:generateDebugResources UP-TO-DATE
        : > Task :integration_test:compileDebugRenderscript NO-SOURCE
        : > Task :integration_test:generateDebugResValues UP-TO-DATE
        : > Task :integration_test:generateDebugResources UP-TO-DATE
        : > Task :integration_test:packageDebugResources UP-TO-DATE
        : > Task :patrol:compileDebugRenderscript NO-SOURCE
        : > Task :patrol:generateDebugResValues UP-TO-DATE
        : > Task :patrol:generateDebugResources UP-TO-DATE
        : > Task :patrol:packageDebugResources UP-TO-DATE
        : > Task :app:mergeDebugResources UP-TO-DATE
        : > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
        : > Task :app:extractDeepLinksDebug UP-TO-DATE
        : > Task :integration_test:extractDeepLinksDebug UP-TO-DATE
        : > Task :integration_test:processDebugManifest UP-TO-DATE
        : > Task :patrol:extractDeepLinksDebug UP-TO-DATE
        : > Task :patrol:processDebugManifest UP-TO-DATE
        : > Task :app:processDebugMainManifest UP-TO-DATE
        : > Task :app:processDebugManifest UP-TO-DATE
        : > Task :app:processDebugManifestForPackage UP-TO-DATE
        : > Task :integration_test:compileDebugLibraryResources UP-TO-DATE
        : > Task :integration_test:parseDebugLocalResources UP-TO-DATE
        : > Task :integration_test:generateDebugRFile UP-TO-DATE
        : > Task :patrol:compileDebugLibraryResources UP-TO-DATE
        : > Task :patrol:parseDebugLocalResources UP-TO-DATE
        : > Task :patrol:generateDebugRFile UP-TO-DATE
        : > Task :app:processDebugResources UP-TO-DATE
        : > Task :integration_test:generateDebugBuildConfig UP-TO-DATE
        : > Task :integration_test:javaPreCompileDebug UP-TO-DATE
        : > Task :integration_test:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :integration_test:bundleLibCompileToJarDebug UP-TO-DATE
        : > Task :patrol:generateDebugBuildConfig UP-TO-DATE
        : > Task :patrol:compileDebugKotlin UP-TO-DATE
        : > Task :patrol:javaPreCompileDebug UP-TO-DATE
        : > Task :patrol:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :patrol:bundleLibCompileToJarDebug UP-TO-DATE
        : > Task :app:compileDebugKotlin
        : > Task :app:javaPreCompileDebug UP-TO-DATE
        : > Task :app:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :app:bundleDebugClasses UP-TO-DATE
        : > Task :app:preDebugAndroidTestBuild SKIPPED
        : > Task :app:compileDebugAndroidTestAidl NO-SOURCE
        : > Task :app:processDebugAndroidTestManifest UP-TO-DATE
        : > Task :app:generateDebugAndroidTestBuildConfig UP-TO-DATE
        : > Task :app:checkDebugAndroidTestAarMetadata UP-TO-DATE
        : > Task :app:compileDebugAndroidTestRenderscript NO-SOURCE
        : > Task :app:generateDebugAndroidTestResValues UP-TO-DATE
        : > Task :app:generateDebugAndroidTestResources UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestResources UP-TO-DATE
        : > Task :app:processDebugAndroidTestResources UP-TO-DATE
        : > Task :app:compileDebugAndroidTestKotlin
        : > Task :app:javaPreCompileDebugAndroidTest UP-TO-DATE
        : > Task :app:compileDebugAndroidTestJavaWithJavac UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestShaders UP-TO-DATE
        : > Task :app:compileDebugAndroidTestShaders NO-SOURCE
        : > Task :app:generateDebugAndroidTestAssets UP-TO-DATE
        : > Task :integration_test:mergeDebugShaders UP-TO-DATE
        : > Task :integration_test:compileDebugShaders NO-SOURCE
        : > Task :integration_test:generateDebugAssets UP-TO-DATE
        : > Task :integration_test:packageDebugAssets UP-TO-DATE
        : > Task :patrol:mergeDebugShaders UP-TO-DATE
        : > Task :patrol:compileDebugShaders NO-SOURCE
        : > Task :patrol:generateDebugAssets UP-TO-DATE
        : > Task :patrol:packageDebugAssets UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestAssets UP-TO-DATE
        : > Task :app:compressDebugAndroidTestAssets UP-TO-DATE
        : > Task :app:processDebugAndroidTestJavaRes NO-SOURCE
        : > Task :integration_test:processDebugJavaRes NO-SOURCE
        : > Task :integration_test:bundleLibResDebug NO-SOURCE
        : > Task :patrol:processDebugJavaRes NO-SOURCE
        : > Task :patrol:bundleLibResDebug UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestJavaResource UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestJniLibFolders UP-TO-DATE
        : > Task :integration_test:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :integration_test:mergeDebugNativeLibs NO-SOURCE
        : > Task :integration_test:copyDebugJniLibsProjectOnly UP-TO-DATE
        : > Task :patrol:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :patrol:mergeDebugNativeLibs NO-SOURCE
        : > Task :patrol:copyDebugJniLibsProjectOnly UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestNativeLibs NO-SOURCE
        : > Task :app:checkDebugAndroidTestDuplicateClasses UP-TO-DATE
        : > Task :app:desugarDebugAndroidTestFileDependencies UP-TO-DATE
        : > Task :app:mergeExtDexDebugAndroidTest UP-TO-DATE
        : > Task :integration_test:bundleLibRuntimeToJarDebug UP-TO-DATE
        : > Task :patrol:bundleLibRuntimeToJarDebug UP-TO-DATE
        : > Task :app:dexBuilderDebugAndroidTest
        : > Task :app:mergeProjectDexDebugAndroidTest UP-TO-DATE
        : > Task :app:validateSigningDebugAndroidTest UP-TO-DATE
        : > Task :app:writeDebugAndroidTestSigningConfigVersions UP-TO-DATE
        : > Task :app:mergeLibDexDebugAndroidTest UP-TO-DATE
        : > Task :app:packageDebugAndroidTest UP-TO-DATE
        : > Task :app:createDebugAndroidTestApkListingFileRedirect UP-TO-DATE
        : > Task :app:assembleDebugAndroidTest UP-TO-DATE
        : 
        : BUILD SUCCESSFUL in 3s
        : 74 actionable tasks: 3 executed, 71 up-to-date
✓ Completed building apk with entrypoint test_bundle.dart (13.6s)
Will uninstall apps before running tests
Uninstalling com.example.integration_test_example from SM A505F
Uninstalling com.example.integration_test_example.test from SM A505F
• Executing tests of apk with entrypoint test_bundle.dart on device R28M30RPKNB...
$ ./gradlew :app:connectedDebugAndroidTest -Ptarget=/home/nabid_admin/Projects/Flutter/integration_test_example/integration_test/test_bundle.dart -Pdart-defines=UEFUUk9MX1dBSVQ9MA==,UEFUUk9MX0FQUF9QQUNLQUdFX05BTUU9Y29tLmV4YW1wbGUuaW50ZWdyYXRpb25fdGVzdF9leGFtcGxl,UEFUUk9MX0FQUF9CVU5ETEVfSUQ9Y29tLmV4YW1wbGUuaW50ZWdyYXRpb25fdGVzdF9leGFtcGxl,UEFUUk9MX0FORFJPSURfQVBQX05BTUU9aW50ZWdyYXRpb25fdGVzdF9leGFtcGxl,UEFUUk9MX0lPU19BUFBfTkFNRT1pbnRlZ3JhdGlvbl90ZXN0X2V4YW1wbGU=,SU5URUdSQVRJT05fVEVTVF9TSE9VTERfUkVQT1JUX1JFU1VMVFNfVE9fTkFUSVZFPWZhbHNl,UEFUUk9MX1RFU1RfTEFCRUxfRU5BQkxFRD10cnVl
        : WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 34
        : 
        : This Android Gradle plugin (7.1.2) was tested up to compileSdk = 32
        : 
        : This warning can be suppressed by adding
        :     android.suppressUnsupportedCompileSdk=34
        : to this project's gradle.properties
        : 
        : The build will continue, but you are strongly encouraged to update your project to
        : use a newer Android Gradle Plugin that has been tested with compileSdk = 34
        : WARNING:We recommend using a newer Android Gradle plugin to use compileSdk = 33
        : 
        : This Android Gradle plugin (7.1.2) was tested up to compileSdk = 32
        : 
        : This warning can be suppressed by adding
        :     android.suppressUnsupportedCompileSdk=33
        : to this project's gradle.properties
        : 
        : The build will continue, but you are strongly encouraged to update your project to
        : use a newer Android Gradle Plugin that has been tested with compileSdk = 33
        : > Task :app:compileFlutterBuildDebug UP-TO-DATE
        : > Task :app:packLibsflutterBuildDebug UP-TO-DATE
        : > Task :app:preBuild UP-TO-DATE
        : > Task :app:preDebugBuild UP-TO-DATE
        : > Task :integration_test:preBuild UP-TO-DATE
        : > Task :integration_test:preDebugBuild UP-TO-DATE
        : > Task :integration_test:compileDebugAidl NO-SOURCE
        : > Task :patrol:preBuild UP-TO-DATE
        : > Task :patrol:preDebugBuild UP-TO-DATE
        : > Task :patrol:compileDebugAidl NO-SOURCE
        : > Task :app:compileDebugAidl NO-SOURCE
        : > Task :integration_test:packageDebugRenderscript NO-SOURCE
        : > Task :patrol:packageDebugRenderscript NO-SOURCE
        : > Task :app:compileDebugRenderscript NO-SOURCE
        : > Task :app:generateDebugBuildConfig UP-TO-DATE
        : > Task :integration_test:writeDebugAarMetadata UP-TO-DATE
        : > Task :patrol:writeDebugAarMetadata UP-TO-DATE
        : > Task :app:checkDebugAarMetadata UP-TO-DATE
        : > Task :app:cleanMergeDebugAssets
        : > Task :app:mergeDebugShaders UP-TO-DATE
        : > Task :app:compileDebugShaders NO-SOURCE
        : > Task :app:generateDebugAssets UP-TO-DATE
        : > Task :integration_test:mergeDebugShaders UP-TO-DATE
        : > Task :integration_test:compileDebugShaders NO-SOURCE
        : > Task :integration_test:generateDebugAssets UP-TO-DATE
        : > Task :integration_test:packageDebugAssets UP-TO-DATE
        : > Task :patrol:mergeDebugShaders UP-TO-DATE
        : > Task :patrol:compileDebugShaders NO-SOURCE
        : > Task :patrol:generateDebugAssets UP-TO-DATE
        : > Task :patrol:packageDebugAssets UP-TO-DATE
        : > Task :app:mergeDebugAssets
        : > Task :app:copyFlutterAssetsDebug
        : > Task :app:generateDebugResValues UP-TO-DATE
        : > Task :app:generateDebugResources UP-TO-DATE
        : > Task :integration_test:compileDebugRenderscript NO-SOURCE
        : > Task :integration_test:generateDebugResValues UP-TO-DATE
        : > Task :integration_test:generateDebugResources UP-TO-DATE
        : > Task :integration_test:packageDebugResources UP-TO-DATE
        : > Task :patrol:compileDebugRenderscript NO-SOURCE
        : > Task :patrol:generateDebugResValues UP-TO-DATE
        : > Task :patrol:generateDebugResources UP-TO-DATE
        : > Task :patrol:packageDebugResources UP-TO-DATE
        : > Task :app:mergeDebugResources UP-TO-DATE
        : > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
        : > Task :app:extractDeepLinksDebug UP-TO-DATE
        : > Task :integration_test:extractDeepLinksDebug UP-TO-DATE
        : > Task :integration_test:processDebugManifest UP-TO-DATE
        : > Task :patrol:extractDeepLinksDebug UP-TO-DATE
        : > Task :patrol:processDebugManifest UP-TO-DATE
        : > Task :app:processDebugMainManifest UP-TO-DATE
        : > Task :app:processDebugManifest UP-TO-DATE
        : > Task :app:processDebugManifestForPackage UP-TO-DATE
        : > Task :integration_test:compileDebugLibraryResources UP-TO-DATE
        : > Task :integration_test:parseDebugLocalResources UP-TO-DATE
        : > Task :integration_test:generateDebugRFile UP-TO-DATE
        : > Task :patrol:compileDebugLibraryResources UP-TO-DATE
        : > Task :patrol:parseDebugLocalResources UP-TO-DATE
        : > Task :patrol:generateDebugRFile UP-TO-DATE
        : > Task :app:processDebugResources UP-TO-DATE
        : > Task :integration_test:generateDebugBuildConfig UP-TO-DATE
        : > Task :integration_test:javaPreCompileDebug UP-TO-DATE
        : > Task :integration_test:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :integration_test:bundleLibCompileToJarDebug UP-TO-DATE
        : > Task :patrol:generateDebugBuildConfig UP-TO-DATE
        : > Task :patrol:compileDebugKotlin UP-TO-DATE
        : > Task :patrol:javaPreCompileDebug UP-TO-DATE
        : > Task :patrol:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :patrol:bundleLibCompileToJarDebug UP-TO-DATE
        : > Task :app:compileDebugKotlin
        : > Task :app:javaPreCompileDebug UP-TO-DATE
        : > Task :app:compileDebugJavaWithJavac UP-TO-DATE
        : > Task :app:bundleDebugClasses UP-TO-DATE
        : > Task :app:preDebugAndroidTestBuild SKIPPED
        : > Task :app:compileDebugAndroidTestAidl NO-SOURCE
        : > Task :app:processDebugAndroidTestManifest UP-TO-DATE
        : > Task :app:generateDebugAndroidTestBuildConfig UP-TO-DATE
        : > Task :app:checkDebugAndroidTestAarMetadata UP-TO-DATE
        : > Task :app:compileDebugAndroidTestRenderscript NO-SOURCE
        : > Task :app:generateDebugAndroidTestResValues UP-TO-DATE
        : > Task :app:generateDebugAndroidTestResources UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestResources UP-TO-DATE
        : > Task :app:processDebugAndroidTestResources UP-TO-DATE
        : > Task :app:compileDebugAndroidTestKotlin
        : > Task :app:javaPreCompileDebugAndroidTest UP-TO-DATE
        : > Task :app:compileDebugAndroidTestJavaWithJavac UP-TO-DATE
        : > Task :app:compressDebugAssets UP-TO-DATE
        : > Task :app:processDebugJavaRes NO-SOURCE
        : > Task :integration_test:processDebugJavaRes NO-SOURCE
        : > Task :integration_test:bundleLibResDebug NO-SOURCE
        : > Task :patrol:processDebugJavaRes NO-SOURCE
        : > Task :patrol:bundleLibResDebug UP-TO-DATE
        : > Task :app:mergeDebugJavaResource UP-TO-DATE
        : > Task :app:checkDebugDuplicateClasses UP-TO-DATE
        : > Task :app:desugarDebugFileDependencies UP-TO-DATE
        : > Task :app:mergeExtDexDebug UP-TO-DATE
        : > Task :integration_test:bundleLibRuntimeToJarDebug UP-TO-DATE
        : > Task :patrol:bundleLibRuntimeToJarDebug UP-TO-DATE
        : > Task :app:dexBuilderDebug UP-TO-DATE
        : > Task :app:mergeLibDexDebug UP-TO-DATE
        : > Task :app:mergeProjectDexDebug UP-TO-DATE
        : > Task :app:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :integration_test:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :integration_test:mergeDebugNativeLibs NO-SOURCE
        : > Task :integration_test:copyDebugJniLibsProjectOnly UP-TO-DATE
        : > Task :patrol:mergeDebugJniLibFolders UP-TO-DATE
        : > Task :patrol:mergeDebugNativeLibs NO-SOURCE
        : > Task :patrol:copyDebugJniLibsProjectOnly UP-TO-DATE
        : > Task :app:mergeDebugNativeLibs UP-TO-DATE
        : > Task :app:stripDebugDebugSymbols UP-TO-DATE
        : > Task :app:validateSigningDebug UP-TO-DATE
        : > Task :app:writeDebugAppMetadata UP-TO-DATE
        : > Task :app:writeDebugSigningConfigVersions UP-TO-DATE
        : > Task :app:packageDebug UP-TO-DATE
        : > Task :app:createDebugApkListingFileRedirect UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestShaders UP-TO-DATE
        : > Task :app:compileDebugAndroidTestShaders NO-SOURCE
        : > Task :app:generateDebugAndroidTestAssets UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestAssets UP-TO-DATE
        : > Task :app:compressDebugAndroidTestAssets UP-TO-DATE
        : > Task :app:processDebugAndroidTestJavaRes NO-SOURCE
        : > Task :app:mergeDebugAndroidTestJavaResource UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestJniLibFolders UP-TO-DATE
        : > Task :app:mergeDebugAndroidTestNativeLibs NO-SOURCE
        : > Task :app:checkDebugAndroidTestDuplicateClasses UP-TO-DATE
        : > Task :app:desugarDebugAndroidTestFileDependencies UP-TO-DATE
        : > Task :app:mergeExtDexDebugAndroidTest UP-TO-DATE
        : > Task :app:mergeLibDexDebugAndroidTest UP-TO-DATE
        : > Task :app:dexBuilderDebugAndroidTest
        : > Task :app:mergeProjectDexDebugAndroidTest UP-TO-DATE
        : > Task :app:validateSigningDebugAndroidTest UP-TO-DATE
        : > Task :app:writeDebugAndroidTestSigningConfigVersions UP-TO-DATE
        : > Task :app:packageDebugAndroidTest UP-TO-DATE
        : > Task :app:createDebugAndroidTestApkListingFileRedirect UP-TO-DATE
        : 
        : > Task :app:connectedDebugAndroidTest
        : Starting 0 tests on SM-A505F - 11
        : 
        : Test results saved as file:/home/nabid_admin/Projects/Flutter/integration_test_example/build/app/outputs/androidTest-results/connected/SM-A505F%20-%2011/test-result.pb. Inspect these results in Android Studio by selecting Run > Import Tests From File from the menu bar and importing test-result.pb.
        : 
        : BUILD SUCCESSFUL in 30s
        : 97 actionable tasks: 7 executed, 90 up-to-date
✓ Completed executing apk with entrypoint test_bundle.dart on device R28M30RPKNB (31.4s)
Uninstalling com.example.integration_test_example from SM A505F
Uninstalling com.example.integration_test_example.test from SM A505F
```

</details>

### Patrol version

patrol: ^2.1.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

Patrol CLI version: 2.0.4
Program adb found in /home/nabid_admin/Android/Sdk/platform-tools/adb
Env var $ANDROID_HOME set to /home/nabid_admin/Android/Sdk
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.10.5, on Ubuntu 22.04 LTS 5.19.0-46-generic, locale en_US.UTF-8)
    • Flutter version 3.10.5 on channel stable at /home/nabid_admin/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (6 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/nabid_admin/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /home/nabid_admin/Android/Sdk
    • Java binary at: /snap/android-studio/126/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /snap/android-studio/126/android-studio
    • Flutter plugin version 74.0.2
    • Dart plugin version 222.4582
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] Connected device (3 available)
    • SM A505F (mobile) • R28M30RPKNB • android-arm64  • Android 11 (API 30)
    • Linux (desktop)   • linux       • linux-x64      • Ubuntu 22.04 LTS 5.19.0-46-generic
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 115.0.5790.102

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by jBorkowska** [comment]
Hi @nbdsunny, thanks for the issue.

We don't have a fix for it yet, and our main developer is on vacation. Will look into it after he's back.

Probably connected to https://github.com/leancodepl/patrol/issues/1455

**Comment by sunnybkash** [comment]
Another information: I have another project with patrol version `^1.0.8` which works fine on the same android 11 device.

**Comment by nbdsunny** [comment]
Another information: I have another project with patrol version `^1.0.8` and that works fine on the same android 11 device.

**Comment by lrorpilla** [comment]
I have similar issues on an Android 10 emulator (`Pixel_2_API_29(AVD) - 10`) and my Pixel 7 Pro running Android 13.

Both have:
```
Instrumentation did not complete:
Instrumentation code: 0
Instrumentation result bundle:
```

I build with `patrol test --flavor [flavor] --target integration_test/[test_name].dart -d [device_name]`, and have followed the current 2.0 docs for setting up on Android.

**Comment by jBorkowska** [comment]
Hi @nbdsunny @lrorpilla, we released new patrol and patrol_cli versions yesterday, that have a fix for your issue. Please check it out and give us some feedback, if it helped.

**Comment by lrorpilla** [comment]
Still the same issue for me on both Android 10 (simulator) and 13 (my Pixel 7 Pro), 
Getting a `Starting 0 tests` issue same as above, already have cleaned and updated package and CLI.

**Comment by jBorkowska** [comment]
@lrorpilla please create new issue and we will investigate your case there
