### ISSUE TITLE
Unable to start test after latest update

### ISSUE THREAD

**Issue by lmlikota** [leancodepl/patrol#573]
Hi @bartekpacia,

I have updated today to latest version. I'm also experimenting with running API calls from test using [dio](https://pub.dev/packages/dio/example) package.

When I try to run my test I'm getting following error:

```
patrol drive --flavor development --verbose --target integration_test/create_intervention_test.dart
Verbose mode enabled. More logs will be printed.
No device specified, using the first one (emulator-5554)
✓ Forwarded ports (83ms)
✓ Installed server (0.5s)
✓ Installed instrumentation (0.6s)
Started native Android instrumentation
> Building apk for create_intervention_test.dart...
ProcessException: The system cannot find the file specified.

  Command: flutter --no-version-check build apk --debug --target C:\Users\lmlikota\haven-holding-mobile\integration_test/create_intervention_test.dart --flavor development --dart-define PATROL_HOST=localhost --dart-define PATROL_PORT=8081 --dart-define PATROL_WAIT=0
See the logs above to learn what happened. If the logs above aren't useful then it's a bug – please report it.
> Running create_intervention_test.dart on emulator-5554...
asset W 11-07 17:07:01 31508 30276] Asset path build/app/outputs/flutter-apk\app-development-debug.apk is neither a directory nor file (type=1).
ERROR: dump failed because assets could not be loaded
Failed to extract manifest from APK: ProcessException: The command failed
  Command: flutter --no-version-check build apk --debug --target C:\Users\lmlikota\haven-holding-mobile\integration_test/app_test.dart --flavor development --dart-define PATROL_HOST=localhost --dart-define PATROL_PORT=8081 --dart-define PATROL_WAIT=0
See the logs above to learn what happened. If the logs above aren't useful then it's a bug – please report it.
> Running app_test.dart on emulator-5554...
asset W 11-07 17:07:36  8624 22908] Asset path build/app/outputs/flutter-apk\app-development-debug.apk is neither a directory nor file (type=1).
ERROR: dump failed because assets could not be loaded
Failed to extract manifest from APK: ProcessException: The command failed
  Command: C:\Users\lmlikota\AppData\Local\Android\sdk\build-tools\32.1.0-rc1\aapt dump xmltree build/app/outputs/flutter-apk\app-development-debug.apk AndroidManifest.xml.
Problem building Android application: see above error(s).
pl.leancode.automatorserver.ServerLoop:
✗ app_test.dart failed
flutter_driver exited with code 1
See the logs above to learn what happened. If the logs above aren't useful then it's a bug – please report it.
Killed native Android instrumentation
Uninstalled instrumentation package pl.leancode.automatorserver.test
Uninstalled server package pl.leancode.automatorserver
Stopped port forwarding
```
Do you have any idea what is going on? I can normally build my app using `flutter build apk --flavor development -t lib/core/environments/main_qa.dart`

**Comment by bartekpacia** [comment]
Hi @lmlikota, sorry for the bug, and thanks for reporting it. I'm pretty sure I introduced it in #552.

Looking into it.

**Comment by bartekpacia** [comment]
Should be fixed in `patrol_cli` v0.7.6+1

**Comment by iEnergyy** [comment]
I had a similar issue after the update, I am currently using v0.7.6+1 and this is the issue that is being returned:

> Building apk for app_test.dart...
ProcessException: The system cannot find the file specified.

the\location\.\integration_test\app_test.dart --dart-define PATROL_HOST=localhost --dart-define PATROL_PORT=8081 --dart-define PATROL_WAIT=0
See the logs above to learn what happened. If the logs above aren't useful then it's a bug – please report it.
> Running app_test.dart on emulator-5554...
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:62725/pEMEPNmS7aI=/
VMServiceFlutterDriver: Isolate found with number: 2722090989120719
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
VMServiceFlutterDriver: Flutter Driver extension is taking a long time to become available. Ensure your test app (often "lib/main.dart") imports "package:flutter_driver/driver_extension.dart" and calls enableFlutterDriverExtension() as the first call in main().
✗ app_test.dart failed
flutter_driver exited with code -1
See the logs above to learn what happened. If the logs above aren't useful then

**Comment by lmlikota** [comment]
@bartekpacia Unfortunately I still can't run test. I have different error now as mentioned by @iEnergyy 

```bash
patrol drive --flavor development --verbose --target integration_test\create_intervention_test.dart
Verbose mode enabled. More logs will be printed.
No device specified, using the first one (emulator-5554)
✓ Forwarded ports (0.1s)
✓ Installed server (0.5s)
✓ Installed instrumentation (1.0s)
Started native Android instrumentation
> Building apk for create_intervention_test.dart...
ProcessException: The system cannot find the file specified.

  Command: flutter --no-version-check build apk --debug --target C:\Users\lmlikota\haven-holding-mobile\integration_test\create_intervention_test.dart --flavor development --dart-define PATROL_HOST=localhost --dart-define PATROL_PORT=8081 --dart-define PATROL_WAIT=0
See the logs above to learn what happened. If the logs above aren't useful then it's a bug – please report it.
> Running create_intervention_test.dart on emulator-5554...
asset W 11-08 15:47:37 15912 31840] Asset path build\app\outputs\flutter-apk\app-development-debug.apk is neither a directory nor file (type=1).
ERROR: dump failed because assets could not be loaded
Failed to extract manifest from APK: ProcessException: The command failed
  Command: C:\Users\lmlikota\AppData\Local\Android\sdk\build-tools\32.1.0-rc1\aapt dump xmltree build\app\outputs\flutter-apk\app-development-debug.apk AndroidManifest.xml.
Problem building Android application: see above error(s).
✗ create_intervention_test.dart failed
flutter_driver exited with code 1
See the logs above to learn what happened. If the logs above aren't useful then it's a bug – please report it.
Killed native Android instrumentation
Uninstalled instrumentation package pl.leancode.automatorserver.test
Uninstalled server package pl.leancode.automatorserver
Stopped port forwarding
```

**Comment by bartekpacia** [comment]
@lmlikota Does the file exist? `build\app\outputs\flutter-apk\app-development-debug.apk`?

**Comment by lmlikota** [comment]
I'm checking that and file does exist but in my case path is: `C:\Users\lmlikota\haven-bridge-mobile\build\app\outputs\flutter-apk\app-development-debug.apk` Looks like it's missing path to the project root?

**Comment by bartekpacia** [comment]
Looks like Windows can't handle relative path in this case.

**Comment by lmlikota** [comment]
Paths, and relative ones, work very similar to what you have in OS X/macOS.

Windows uses "\", not "/".
Basically ".." is one level higher
".\" is a sub-folder of the current working directory 

This is from https://superuser.com/questions/1270591/how-to-use-relative-paths-on-windows-cmd

**Comment by lmlikota** [comment]
Hi @bartekpacia,

we have some progress regarding this issue. Actually looks like we have fixed problem with relative path on Windows with this change in `flutter_tool.dart` on line 238.

```dart  
        final prefix = absolute(join('build', 'app', 'outputs', 'flutter-apk'));
```
But unfortunately we have stumbled upon another issue with `PatrolBinding` while running our test

```bash
 patrol drive --flavor development --verbose --target integration_test\create_intervention_test.dart
Verbose mode enabled. More logs will be printed.
No device specified, using the first one (emulator-5554)
✓ Forwarded ports (0.1s)
✓ Installed server (0.6s)
✓ Installed instrumentation (0.8s)
Started native Android instrumentation
> Building apk for create_intervention_test.dart...
pl.leancode.automatorserver.ServerLoop:

Building with sound null safety

Running Gradle task 'assembleDevelopmentDebug'...
14,8s
âˆš  Built build\app\outputs\flutter-apk\app-development-debug.apk.
✓ Building apk for create_intervention_test.dart succeeded!
> Running create_intervention_test.dart on emulator-5554...
Installing build\app\outputs\flutter-apk\app-development-debug.apk...
1.706ms
W/ven_holding.de( 8093): Accessing hidden method Landroid/os/WorkSource;->add(I)Z (unsupported,test-api, reflection, allowed)
W/ven_holding.de( 8093): Accessing hidden method Landroid/os/WorkSource;->add(ILjava/lang/String;)Z (unsupported,test-api, reflection, allowed)
W/ven_holding.de( 8093): Accessing hidden method Landroid/os/WorkSource;->get(I)I (unsupported, reflection, allowed)
W/ven_holding.de( 8093): Accessing hidden method Landroid/os/WorkSource;->getName(I)Ljava/lang/String; (unsupported, reflection, allowed)
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:52363/Z5J6G0RC8vo=/
VMServiceFlutterDriver: Isolate found with number: 851346242011535
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
Patrol: creating NativeAutomator
        host: localhost
        port: 8081
        packageName: hr.biss.haven_holding.dev
        bundleId: hr.biss.havenHolding.dev
Patrol: Initializing PatrolBinding...
E/flutter ( 8093): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/foundation/binding.dart': Failed assertion: line 146 pos 12: '_debugInitializedType == null': is not true.
E/flutter ( 8093): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter ( 8093): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter ( 8093): #2      new BindingBase (package:flutter/src/foundation/binding.dart:146:12)
E/flutter ( 8093): #3      new _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding (package:flutter_test/src/binding.dart)
E/flutter ( 8093): #4      new _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding&ServicesBinding (package:flutter_test/src/binding.dart)
E/flutter ( 8093): #5      new _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding&ServicesBinding&GestureBinding (package:flutter_test/src/binding.dart)
E/flutter ( 8093): #6      new _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding&ServicesBinding&GestureBinding&SemanticsBinding (package:flutter_test/src/binding.dart)
E/flutter ( 8093): #7      new _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding&ServicesBinding&GestureBinding&SemanticsBinding&RendererBinding (package:flutter_test/src/binding.dart)
E/flutter ( 8093): #8      new _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding&ServicesBinding&GestureBinding&SemanticsBinding&RendererBinding&PaintingBinding (package:flutter_test/src/binding.dart)
E/flutter ( 8093): #9      new _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding&ServicesBinding&GestureBinding&SemanticsBinding&RendererBinding&PaintingBinding&WidgetsBinding (package:flutter_test/src/binding.dart)
E/flutter ( 8093): #10     new _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding&ServicesBinding&GestureBinding&SemanticsBinding&RendererBinding&PaintingBinding&WidgetsBinding&TestDefaultBinaryMessengerBinding (package:flutter_test/src/binding.dart)
E/flutter ( 8093): #16     new NativeAutomator (package:patrol/src/native/native_automator.dart:96:23)
E/flutter ( 8093): #17     patrolTest (package:patrol/src/custom_finders/common.dart:40:9)
E/flutter ( 8093): #18     main (file:///C:/Users/lmlikota/haven-holding-mobile/integration_test/create_intervention_test.dart:11:3)
E/flutter ( 8093): #19     _runMain.<anonymous closure> (dart:ui/hooks.dart:134:23)
E/flutter ( 8093): #20     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
E/flutter ( 8093): #21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
E/flutter ( 8093):
00:00 +0: (tearDownAll)
VMServiceFlutterDriver: Connected to Flutter application.
00:00 +1: All tests passed!
All tests passed.
✓ create_intervention_test.dart passed!
Killed native Android instrumentation
Uninstalled instrumentation package pl.leancode.automatorserver.test
Uninstalled server package pl.leancode.automatorserver
Stopped port forwarding
```
I hope this helps a bit.

**Comment by bartekpacia** [comment]
@lmlikota Thanks a lot for the fix, I created #586 to introduce your fix.

**Comment by bartekpacia** [comment]
Regarding the crash from [this comment](https://github.com/leancodepl/patrol/issues/573#issuecomment-1308675290):

The `'_debugInitializedType == null': is not true` occurs when you initialize bindings before Patrol initializes its own binding. Maybe this is a bug but first I'd like to ask you for the Dart test target file you're running (`create_intervention_test.dart`).

**Comment by lmlikota** [comment]
> Regarding the crash from [this comment](https://github.com/leancodepl/patrol/issues/573#issuecomment-1308675290):
> 
> The `'_debugInitializedType == null': is not true` occurs when you initialize bindings before Patrol initializes its own binding. Maybe this is a bug but first I'd like to ask you to share the Dart test target file you're running (`create_intervention_test.dart`).

You are right, i have commented out 
```dart

Future<void> main() async {
  //IntegrationTestWidgetsFlutterBinding.ensureInitialized();  => I'm not even sure do I need this in first place, looks like not really
  patrolTest('sign in', config: patrolConfig, nativeAutomation: true,
      ($) async {
    app.main();
```

**Comment by lmlikota** [comment]
I mean it's not a bug it's probably just me, after commenting out my test has passed 😃 
```bash
 patrol drive --flavor development --verbose --target integration_test\create_intervention_test.dart
Verbose mode enabled. More logs will be printed.
No device specified, using the first one (emulator-5554)
✓ Forwarded ports (0.1s)
✓ Installed server (0.9s)
✓ Installed instrumentation (1.1s)
Started native Android instrumentation
> Building apk for create_intervention_test.dart...

Building with sound null safety

Running Gradle task 'assembleDevelopmentDebug'...
pl.leancode.automatorserver.ServerLoop:
20,8s
âˆš  Built build\app\outputs\flutter-apk\app-development-debug.apk.
✓ Building apk for create_intervention_test.dart succeeded!
> Running create_intervention_test.dart on emulator-5554...
Installing build\app\outputs\flutter-apk\app-development-debug.apk...
2.510ms
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:60101/HcSS9PBgank=/
VMServiceFlutterDriver: Isolate found with number: 1069006792052387
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
Patrol: creating NativeAutomator
        host: localhost
        port: 8081
        packageName: hr.biss.haven_holding.dev
        bundleId: hr.biss.havenHolding.dev
Patrol: Initializing PatrolBinding...
00:00 +0: sign in
D/InputMethodManager( 9322): showSoftInput() view=io.flutter.embedding.android.FlutterView{2497743 VFE...... .F....ID 0,0-1080,2148 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InputMethodManager( 9322): showSoftInput() view=io.flutter.embedding.android.FlutterView{2497743 VFE...... .F...... 0,0-1080,2148 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/EGL_emulation( 9322): app_time_stats: avg=239.46ms min=7.79ms max=409.23ms count=5
D/InputMethodManager( 9322): showSoftInput() view=io.flutter.embedding.android.FlutterView{2497743 VFE...... .F...... 0,0-1080,2148 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InputMethodManager( 9322): showSoftInput() view=io.flutter.embedding.android.FlutterView{2497743 VFE...... .F...... 0,0-1080,2148 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InputMethodManager( 9322): showSoftInput() view=io.flutter.embedding.android.FlutterView{2497743 VFE...... .F...... 0,0-1080,2148 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InputMethodManager( 9322): showSoftInput() view=io.flutter.embedding.android.FlutterView{2497743 VFE...... .F...... 0,0-1080,2148 #1 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/EGL_emulation( 9322): app_time_stats: avg=253.07ms min=183.14ms max=345.97ms count=5
D/InsetsController( 9322): show(ime(), fromIme=true)
D/EGL_emulation( 9322): app_time_stats: avg=2902.03ms min=2213.30ms max=3590.77ms count=2
D/EGL_emulation( 9322): app_time_stats: avg=155.24ms min=21.73ms max=246.49ms count=7
D/EGL_emulation( 9322): app_time_stats: avg=217.75ms min=23.16ms max=487.33ms count=5
00:07 +1: (tearDownAll)
00:07 +2: All tests passed!
All tests passed.
✓ create_intervention_test.dart passed!
Killed native Android instrumentation
Uninstalled instrumentation package pl.leancode.automatorserver.test
Uninstalled server package pl.leancode.automatorserver
Stopped port forwarding
```
